Repository the-events-calendar/tec-testing-facilities, pull requests merged in 2019-08, with the labels that each got.

#5 Use the template variables from the view to setup the template variables
  src/Products/WPBrowser/Views/V2/HtmlTestCase.php
Labels: code review

#6 feat(Views v2) add start_of_week default mock
  src/Products/WPBrowser/Views/V2/TestCase.php
  src/Products/WPBrowser/Views/V2/ViewTestCase.php
Labels: code review, merge

#7 Updates to the With_Post_Remapping trait
  src/PHPUnit/Traits/With_Post_Remapping.php
Labels: code review, merge

#8 feat(With_Post_Remapping) add get_mock_event method
  src/PHPUnit/Traits/With_Post_Remapping.php
Labels: code review, merge

#9 feat(With_Filter_Manipulation) adds the trait
  docs/PHPUnit/Traits/With_Filter_Manipulation.md
  docs/README.md
  src/PHPUnit/Traits/With_Filter_Manipulation.php
Labels: merge
